[package]
name = "blockchain_rust"
version = "0.1.0"
authors = ["akht <picopeko@gmail.com>"]
edition = "2018"

[dependencies]
iron = "*"
router = "*"
rust-crypto = "*"
rustc-serialize = "*"
serde_json = "*"
serde = "*"
serde_derive = "*"